package net.mv.expectedException;

import org.junit.Test;

public class JUnitTest2 {

	@Test(expected = ArithmeticException.class)
	public void divisionWithException() {
		System.out.println("@Test - Bypass the Arithmetic Exception throw");
		int num = 1/0;
	}
	
	
}
